# Pandas DataFrame


In [6]:
# import pandas libarary
import pandas as pd
##how to create a series
item=['l1','l2','l3','l4']
s=pd.Series(item)
print(s)
print(s[1:3])

0    l1
1    l2
2    l3
3    l4
dtype: object
1    l2
2    l3
dtype: object


In [5]:
# Example of how a dataframe can be created with 4 rows and 2 column
x=pd.DataFrame({'a':[1,2,3,4], 'b' : ['ch','ag','tp','ff']})
print(x)

   a   b
0  1  ch
1  2  ag
2  3  tp
3  4  ff


In [2]:
# read the data from text,csv,excel,json with the help of pandas
#we can view,slicing,indexing,select,conditional filter ,aggregrating,grouping,merging,sorting on the data
#detect missing value ,remove it
import pandas as pd
file ="C:\\Users\\Lenovo\\bike.csv"    # provide file path
# we need to provide file path from where we need to import the data
df=pd.read_csv(file,sep=',')
df.head(10)

# we have two additiional  parameter in pd.read_csv is nrows and skiprows skiprws will skip first n number of roes
# nrows willl fetch fist n number of rows. 


ID Marital Status  Gender    Income  Children            Education  \
0  12496        Married  Female   40000.0       1.0            Bachelors   
1  24107        Married    Male   30000.0       3.0      Partial College   
2  14177        Married    Male   80000.0       5.0      Partial College   
3  24381         Single     NaN   70000.0       0.0            Bachelors   
4  25597         Single    Male   30000.0       0.0            Bachelors   
5  13507        Married  Female   10000.0       2.0      Partial College   
6  27974         Single    Male  160000.0       2.0          High School   
7  19364        Married    Male   40000.0       1.0            Bachelors   
8  22155            NaN    Male   20000.0       2.0  Partial High School   
9  19280        Married    Male       NaN       2.0      Partial College   

       Occupation Home Owner  Cars Commute Distance   Region   Age  \
0  Skilled Manual        Yes   0.0        0-1 Miles   Europe  42.0   
1        Clerical        Yes   1.0        0-1 Miles   Europe  43.0   
2    Professional         No   2.0        2-5 Miles   Europe  60.0   
3    Professional        Yes   1.0       5-10 Miles  Pacific  41.0   
4        Clerical         No   0.0        0-1 Miles   Europe  36.0   
5          Manual        Yes   0.0        1-2 Miles   Europe  50.0   
6      Management        NaN   4.0        0-1 Miles  Pacific  33.0   
7  Skilled Manual        Yes   0.0        0-1 Miles   Europe  43.0   
8        Clerical        Yes   2.0       5-10 Miles  Pacific  58.0   
9          Manual        Yes   1.0        0-1 Miles   Europe   NaN   

  Purchased Bike  
0             No  
1             No  
2             No  
3            Yes  
4            Yes  
5             No  
6            Yes  
7            Yes  
8             No  
9            Yes

In [4]:
df.shape
#provide rows and column count

(1000, 13)

In [5]:
df.size
#provide rows*columns

13000

In [6]:
df.describe()
#describe some statistics value on the dataset

ID         Income    Children        Cars         Age
count   1000.000000     994.000000  992.000000  991.000000  992.000000
mean   19965.992000   56267.605634    1.910282    1.455096   44.181452
std     5347.333948   31067.817462    1.626910    1.121755   11.362007
min    11000.000000   10000.000000    0.000000    0.000000   25.000000
25%    15290.750000   30000.000000    0.000000    1.000000   35.000000
50%    19744.000000   60000.000000    2.000000    1.000000   43.000000
75%    24470.750000   70000.000000    3.000000    2.000000   52.000000
max    29447.000000  170000.000000    5.000000    4.000000   89.000000

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   ID                1000 non-null   int64  
 1   Marital Status    993 non-null    object 
 2   Gender            989 non-null    object 
 3   Income            994 non-null    float64
 4   Children          992 non-null    float64
 5   Education         1000 non-null   object 
 6   Occupation        1000 non-null   object 
 7   Home Owner        996 non-null    object 
 8   Cars              991 non-null    float64
 9   Commute Distance  1000 non-null   object 
 10  Region            1000 non-null   object 
 11  Age               992 non-null    float64
 12  Purchased Bike    1000 non-null   object 
dtypes: float64(4), int64(1), object(8)
memory usage: 101.7+ KB


In [7]:
print(df.columns)
#provide all column names

Index(['ID', 'Marital Status', 'Gender', 'Income', 'Children', 'Education',
       'Occupation', 'Home Owner', 'Cars', 'Commute Distance', 'Region', 'Age',
       'Purchased Bike'],
      dtype='object')


In [9]:
#acces a particular coloumn
df['Age']

0      42.0
1      43.0
2      60.0
3      41.0
4      36.0
       ... 
995    54.0
996    35.0
997    38.0
998    38.0
999    53.0
Name: Age, Length: 1000, dtype: float64

In [ ]:
#access more than 1 column
print(df[['age']])
#access column names
df[['age','job']]

In [ ]:
# How to filter the data on the basis of some condition
df[ df['age']> 44 ]
df[  (df['age']> 44) &  (df['education']== 'primary') ]

In [10]:
# slicing and indexing if the data through iloc and loc
df.iloc[1:4]

ID Marital Status Gender   Income  Children        Education  \
1  24107        Married   Male  30000.0       3.0  Partial College   
2  14177        Married   Male  80000.0       5.0  Partial College   
3  24381         Single    NaN  70000.0       0.0        Bachelors   

     Occupation Home Owner  Cars Commute Distance   Region   Age  \
1      Clerical        Yes   1.0        0-1 Miles   Europe  43.0   
2  Professional         No   2.0        2-5 Miles   Europe  60.0   
3  Professional        Yes   1.0       5-10 Miles  Pacific  41.0   

  Purchased Bike  
1             No  
2             No  
3            Yes

In [11]:
df.iloc[1:4,1:5]
df.iloc[2,3]

Marital Status Gender   Income  Children
1        Married   Male  30000.0       3.0
2        Married   Male  80000.0       5.0
3         Single    NaN  70000.0       0.0

In [22]:
df.loc[2]

ID                            14177
Marital Status              Married
Gender                         Male
Income                      80000.0
Children                        5.0
Education           Partial College
Occupation             Professional
Home Owner                       No
Cars                            2.0
Commute Distance          2-5 Miles
Region                       Europe
Age                            60.0
Purchased Bike                   No
Name: 2, dtype: object

In [ ]:
df.loc[2,]
df.loc[2,:]

In [ ]:
df.loc[4,'age':'balance']
df.loc[2:4,['age','balance']]

In [18]:
df['new'] = df['Age'].apply(lambda x: x>42.0)
print(df.head(10))

      ID Marital Status  Gender    Income  Children            Education  \
0  12496        Married  Female   40000.0       1.0            Bachelors   
1  24107        Married    Male   30000.0       3.0      Partial College   
2  14177        Married    Male   80000.0       5.0      Partial College   
3  24381         Single     NaN   70000.0       0.0            Bachelors   
4  25597         Single    Male   30000.0       0.0            Bachelors   
5  13507        Married  Female   10000.0       2.0      Partial College   
6  27974         Single    Male  160000.0       2.0          High School   
7  19364        Married    Male   40000.0       1.0            Bachelors   
8  22155            NaN    Male   20000.0       2.0  Partial High School   
9  19280        Married    Male       NaN       2.0      Partial College   

       Occupation Home Owner  Cars Commute Distance   Region   Age  \
0  Skilled Manual        Yes   0.0        0-1 Miles   Europe  42.0   
1        Clerical      

In [6]:
#Rename columns
df=df.rename(columns={'ID' :'Number', 'Income' : 'Salary'})
print(df)

ID Marital Status Gender   Income  Children        Education  \
1  24107        Married   Male  30000.0       3.0  Partial College   
2  14177        Married   Male  80000.0       5.0  Partial College   
3  24381         Single    NaN  70000.0       0.0        Bachelors   

     Occupation Home Owner  Cars Commute Distance   Region   Age  \
1      Clerical        Yes   1.0        0-1 Miles   Europe  43.0   
2  Professional         No   2.0        2-5 Miles   Europe  60.0   
3  Professional        Yes   1.0       5-10 Miles  Pacific  41.0   

  Purchased Bike  
1             No  
2             No  
3            Yes

In [12]:
# Total number of rows matching a specefic creteria
row_numbers=df[ (df['Marital Status']=='Married')  & (df['Children']== 1.0 )].index
print(len(row_numbers))

119


In [15]:
#sort in descending order
small=df.sort_values(by='Age', ascending=True)#sort in ascending order
small.head(n=10)

ID Marital Status  Gender   Income  Children            Education  \
164  22402        Married    Male  10000.0       0.0      Partial College   
165  15465        Married  Female  10000.0       0.0      Partial College   
217  13673         Single  Female  20000.0       NaN  Partial High School   
798  22971         Single  Female  30000.0       0.0          High School   
195  25559         Single    Male  20000.0       0.0            Bachelors   
237  25555        Married  Female  10000.0       0.0      Partial College   
85   16514         Single    Male  10000.0       0.0      Partial College   
219  22399         Single    Male  10000.0       0.0      Partial College   
326  20994        Married  Female  20000.0       0.0            Bachelors   
207  28729         Single  Female  20000.0       0.0  Partial High School   

         Occupation Home Owner  Cars Commute Distance         Region   Age  \
164          Manual        Yes   1.0        2-5 Miles        Pacific  25.0   
165          Manual         No   1.0        0-1 Miles        Pacific  25.0   
217          Manual         No   2.0        0-1 Miles         Europe  25.0   
798  Skilled Manual         No   2.0        0-1 Miles  North America  25.0   
195        Clerical        Yes   0.0        0-1 Miles        Pacific  25.0   
237          Manual         No   1.0        0-1 Miles        Pacific  26.0   
85           Manual        Yes   1.0        1-2 Miles        Pacific  26.0   
219          Manual        Yes   1.0        1-2 Miles        Pacific  26.0   
326        Clerical         No   0.0        0-1 Miles        Pacific  26.0   
207          Manual        Yes   2.0        1-2 Miles         Europe  26.0   

    Purchased Bike  
164            Yes  
165             No  
217             No  
798            Yes  
195            Yes  
237            Yes  
85             Yes  
219            Yes  
326            Yes  
207            Yes

In [ ]:
# Replacing the value
df['Occupation']= df['Occupation'].replace(to_replace='Professional',value='Professionalqw')  
print(df.head(12))

In [18]:
df['Gender'].unique()

array(['Female', 'Male', nan], dtype=object)

In [21]:
x6=df['Gender'].nunique()
print(x6)

2


In [16]:
df['mRank'] = df['Age'].rank(ascending=True)
df1 = df[df['mRank'] == '1.0']
print(df1)

Empty DataFrame
Columns: [ID, Marital Status, Gender, Income, Children, Education, Occupation, Home Owner, Cars, Commute Distance, Region, Age, Purchased Bike, mRank]
Index: []


In [45]:
df[['age','job']][2:5]
#iloc ends index-1  but loc gives exact values since it is on labels
df.iloc[1:4]
df.iloc[1:4,1:5]
df.loc[2]
df.loc[4,]
df.loc[4,'age':'balance']
df.loc[2:4,['age','balance']]

df[df['age']> 44]
l=df[df['age']> 44].index
print(l)
b=df.head(13)
print(b)

#large=data.sort_values(by='Number of speakers', ascending=False)#sort in descending order
#large.head(n=10)
 

Int64Index([    0,     3,     8,    12,    13,    14,    15,    16,    17,
               18,
            ...
            45186, 45191, 45194, 45195, 45201, 45204, 45206, 45207, 45208,
            45209],
           dtype='int64', length=15664)
    age           job   marital  education default  balance housing loan  \
0    58    management   married   tertiary      no     2143     yes   no   
1    44    technician    single  secondary      no       29     yes   no   
2    33  entrepreneur   married  secondary      no        2     yes  yes   
3    47   blue-collar   married    unknown      no     1506     yes   no   
4    33       unknown    single    unknown      no        1      no   no   
5    35    management   married   tertiary      no      231     yes   no   
6    28    management    single   tertiary      no      447     yes  yes   
7    42  entrepreneur  divorced   tertiary     yes        2     yes   no   
8    58       retired   married    primary      no      121     yes   n

age  job           marital  education  default  balance  housing  loan  contact  day  month  durations  campaign  pdays  previous  poutcome  y 
33   entrepreneur  married  secondary  no       2        yes      yes   unknown  5    may    76         1         -1     0         unknown   no    1
     unknown       single   unknown    no       1        no       no    unknown  5    may    198        1         -1     0         unknown   no    1
dtype: int64

# len vs count vs shape
# count method ignore the rows which have missing values.
print(df.count())
print(len(df.index))


In [50]:
print(b['age'].value_counts())

58    2
33    2
44    1
47    1
35    1
28    1
42    1
43    1
41    1
29    1
53    1
Name: age, dtype: int64


In [ ]:
print(df.count())
print(len(df.index))

# Aggregating the data

In [ ]:
x5=df.groupby('marital')['balance'].mean()
print(x5)
x5=df.groupby('marital')['balance']
print(x5)


a=data.groupby(['marital']).size()
print(df.groupby(['Gender','Marital Status'])['Income'].sum())
print(a)

In [53]:
byStatus = df.groupby('marital') 
byStatus.head(n=10)

age           job   marital  education default  balance housing loan  \
0    58    management   married   tertiary      no     2143     yes   no   
1    44    technician    single  secondary      no       29     yes   no   
2    33  entrepreneur   married  secondary      no        2     yes  yes   
3    47   blue-collar   married    unknown      no     1506     yes   no   
4    33       unknown    single    unknown      no        1      no   no   
5    35    management   married   tertiary      no      231     yes   no   
6    28    management    single   tertiary      no      447     yes  yes   
7    42  entrepreneur  divorced   tertiary     yes        2     yes   no   
8    58       retired   married    primary      no      121     yes   no   
9    43    technician    single  secondary      no      593     yes   no   
10   41        admin.  divorced  secondary      no      270     yes   no   
11   29        admin.    single  secondary      no      390     yes   no   
12   53    technician   married  secondary      no        6     yes   no   
13   58    technician   married    unknown      no       71     yes   no   
14   57      services   married  secondary      no      162     yes   no   
15   51       retired   married    primary      no      229     yes   no   
16   45        admin.    single    unknown      no       13     yes   no   
17   57   blue-collar   married    primary      no       52     yes   no   
22   32   blue-collar    single    primary      no       23     yes  yes   
26   39    management    single   tertiary      no      255     yes   no   
28   46    management    single  secondary      no     -246     yes   no   
29   36    technician    single  secondary      no      265     yes  yes   
35   57    technician  divorced  secondary      no       63     yes   no   
38   36        admin.  divorced  secondary      no      506     yes   no   
40   44      services  divorced  secondary      no     2586     yes   no   
48   55    technician  divorced  secondary      no        0      no   no   
51   48    management  divorced   tertiary      no     -244     yes   no   
61   53    technician  divorced  secondary      no      989     yes   no   
67   59    management  divorced   tertiary      no       59     yes   no   
77   55      services  divorced  secondary      no       91      no   no   

    contact  day month  durations  campaign  pdays  previous poutcome   y  
0   unknown    5   may        261         1     -1         0  unknown  no  
1   unknown    5   may        151         1     -1         0  unknown  no  
2   unknown    5   may         76         1     -1         0  unknown  no  
3   unknown    5   may         92         1     -1         0  unknown  no  
4   unknown    5   may        198         1     -1         0  unknown  no  
5   unknown    5   may        139         1     -1         0  unknown  no  
6   unknown    5   may        217         1     -1         0  unknown  no  
7   unknown    5   may        380         1     -1         0  unknown  no  
8   unknown    5   may         50         1     -1         0  unknown  no  
9   unknown    5   may         55         1     -1         0  unknown  no  
10  unknown    5   may        222         1     -1         0  unknown  no  
11  unknown    5   may        137         1     -1         0  unknown  no  
12  unknown    5   may        517         1     -1         0  unknown  no  
13  unknown    5   may         71         1     -1         0  unknown  no  
14  unknown    5   may        174         1     -1         0  unknown  no  
15  unknown    5   may        353         1     -1         0  unknown  no  
16  unknown    5   may         98         1     -1         0  unknown  no  
17  unknown    5   may         38         1     -1         0  unknown  no  
22  unknown    5   may        160         1     -1         0  unknown  no  
26  unknown    5   may        296         1     -1         0  unknown  no  
28  unknown    5   may        255         2     -1 

In [54]:
df.groupby(['education']).count()

age    job  marital  default  balance  housing   loan  contact  \
education                                                                     
primary     6851   6851     6851     6851     6851     6851   6851     6851   
secondary  23201  23201    23201    23201    23201    23201  23201    23201   
tertiary   13301  13301    13301    13301    13301    13301  13301    13301   
unknown     1857   1857     1857     1857     1857     1857   1857     1857   

             day  month  durations  campaign  pdays  previous  poutcome      y  
education                                                                       
primary     6851   6851       6851      6851   6851      6851      6851   6851  
secondary  23201  23201      23201     23201  23201     23201     23201  23201  
tertiary   13301  13301      13301     13301  13301     13301     13301  13301  
unknown     1857   1857       1857      1857   1857      1857      1857   1857

In [8]:
data.groupby(['Countries','Degree of endangerment']).count()

ID  \
Countries                                          Degree of endangerment       
Afghanistan                                        Critically endangered    2   
                                                   Definitely endangered    5   
                                                   Severely endangered      4   
                                                   Vulnerable               1   
Albania, Algeria, Bosnia and Herzegovina, Bulga... Severely endangered      1   
Albania, Bulgaria, Greece, The former Yugoslav ... Definitely endangered    1   
Albania, Bulgaria, The former Yugoslav Republic... Vulnerable               1   
Albania, Germany, Austria, Belarus, Bosnia and ... Definitely endangered    1   
Algeria                                            Critically endangered    3   
                                                   Severely endangered      5   
                                                   Vulnerable               4   
Angola                                             Definitely endangered    1   
                                                   Extinct                  3   
Argentina                                          Critically endangered    2   
                                                   Definitely endangered    4   
                                                   Extinct                  3   
                                                   Severely endangered      1   
                                                   Vulnerable               1   
Argentina, Bolivia (Plurinational State of)        Vulnerable               2   
Argentina, Bolivia (Plurinational State of), Chile Extinct                  1   
Argentina, Bolivia (Plurinational State of), Pa... Definitely endangered    1   
                                                   Severely endangered      1   
Argentina, Paraguay                                Severely endangered      1   
Argentina, Uruguay                                 Severely endangered      1   
Armenia, Georgia, Greece, Russian Federation, T... Definitely endangered    1   
Armenia, Iran (Islamic Republic of), Iraq, Syri... Definitely endangered    1   
Australia                                          Critically endangered   42   
                                                   Definitely endangered   13   
                                                   Extinct                  6   
                                                   Severely endangered     30   
...                                                                        ..   
United Kingdom of Great Britain and Northern Ir... Vulnerable               2   
United Republic of Tanzania                        Critically endangered    2   
                                                   Definitely endangered    2   
                                                   Extinct                  2   
                                                   Severely endangered      2   
                                                   Vulnerable               3   
United States of America                           Critically endangered   80   
                                                   Definitely endangered   28   
                                                   Extinct                 54   
                                                   Severely endangered     40   
                                                   Vulnerable              14   
Uzbekistan                                         Definitely endangered    1   
Uzbekistan, Tajikistan, Afghanistan                Definitely endangered    1   
                                                   Severely endangered      1   
Vanuatu                                            Critically endangered   22   
                                                   Definitely endangered   10   
                                                   Extinct                  3   
                         

### lambda functions

#### identify which languages have fewer then 5k speakers

In [10]:
data['vfew'] = data['Number of speakers'].apply(lambda x: x <= 5000)

In [11]:
data.head(n=6) 

ID Name in English                                          Countries  \
0  1022   South Italian                                              Italy   
1  1023        Sicilian                                              Italy   
2   383       Low Saxon  Germany, Denmark, Netherlands, Poland, Russian...   
3   335      Belarusian  Belarus, Latvia, Lithuania, Poland, Russian Fe...   
4   382         Lombard                                 Italy, Switzerland   
5   405          Romani  Albania, Germany, Austria, Belarus, Bosnia and...   

                               Country codes alpha 3 Degree of endangerment  \
0                                                ITA             Vulnerable   
1                                                ITA             Vulnerable   
2                            DEU, DNK, NLD, POL, RUS             Vulnerable   
3                       BRB, LVA, LTU, POL, RUS, UKR             Vulnerable   
4                                           ITA, CHE  Definitely endangered   
5  ALB, DEU, AUT, BRB, BIH, BGR, HRV, EST, FIN, F...  Definitely endangered   

   Number of speakers  Latitude  Longitude  \
0           7500000.0   40.9798    15.2490   
1           5000000.0   37.4399    14.5019   
2           4800000.0   53.4029    10.3601   
3           4000000.0   53.9560    27.5756   
4           3500000.0   45.7215     9.3273   
5           3500000.0   46.3165    22.3681   

                         Description of the location   vfew  
0  Campania, Lucania (Basilicata), Abruzzi (Abruz...  False  
1  Sicily (Sicilia), southern and central Calabri...  False  
2  northern Germany, the north-eastern part of th...  False  
3  Belarus except the Polesian-speaking south-wes...  False  
4  the region of Lombardy (except the southernmos...  False  
5  many European countries, most densely in East-...  False

In [12]:
group_by_5k = data.groupby(['vfew'])

In [13]:
group_by_5k.size()

vfew
False     879
True     1843
dtype: int64

In [14]:
group_by_5kC = data.groupby(['vfew','Countries'])

In [15]:
group_by_5kC.size()

vfew   Countries                                                                                                                                                                                                                                                                                                                                                                                  
False  Afghanistan                                                                                                                                                                                                                                                                                                                                                                                      2
       Albania, Algeria, Bosnia and Herzegovina, Bulgaria, Croatia, Greece, The former Yugoslav Republic of Macedonia, Morocco, Romania, Turkey, Serbia                                                                    

In [16]:
data['Degree of endangerment'].value_counts() 

Definitely endangered    680
Vulnerable               628
Critically endangered    607
Severely endangered      554
Extinct                  253
Name: Degree of endangerment, dtype: int64

In [5]:
import os
os.getcwd()
import pandas as pd


age           job   marital  education default  balance housing loan  \
0   58    management   married   tertiary      no     2143     yes   no   
1   44    technician    single  secondary      no       29     yes   no   
2   33  entrepreneur   married  secondary      no        2     yes  yes   
3   47   blue-collar   married    unknown      no     1506     yes   no   
4   33       unknown    single    unknown      no        1      no   no   
5   35    management   married   tertiary      no      231     yes   no   
6   28    management    single   tertiary      no      447     yes  yes   
7   42  entrepreneur  divorced   tertiary     yes        2     yes   no   
8   58       retired   married    primary      no      121     yes   no   
9   43    technician    single  secondary      no      593     yes   no   

   contact  day month  durations  campaign  pdays  previous poutcome   y  
0  unknown    5   may        261         1     -1         0  unknown  no  
1  unknown    5   may        151         1     -1         0  unknown  no  
2  unknown    5   may         76         1     -1         0  unknown  no  
3  unknown    5   may         92         1     -1         0  unknown  no  
4  unknown    5   may        198         1     -1         0  unknown  no  
5  unknown    5   may        139         1     -1         0  unknown  no  
6  unknown    5   may        217         1     -1         0  unknown  no  
7  unknown    5   may        380         1     -1         0  unknown  no  
8  unknown    5   may         50         1     -1         0  unknown  no  
9  unknown    5   may         55         1     -1         0  unknown  no

In [8]:
x1=pd.pivot_table(
              
             data=df,
             index= 'marital'

             )
print(x1.head(10))

                age      balance  campaign        day   durations      pdays  \
marital                                                                        
divorced  45.782984  1178.872287  2.630882  15.796428  262.517188  41.001728   
married   43.408334  1425.868813  2.842906  15.854445  253.408812  37.944953   
single    33.703440  1301.497654  2.649805  15.708210  266.497967  44.652385   

          previous  
marital             
divorced  0.551373  
married   0.556168  
single    0.642690  


In [11]:
x2=pd.pivot_table(
      data=df,
      index= 'marital',
      values='balance',
       aggfunc='sum')
print(x2.head(10))
print(df.head(10))

           balance
marital           
divorced   6138388
married   38802168
single    16646155
   age           job   marital  education default  balance housing loan  \
0   58    management   married   tertiary      no     2143     yes   no   
1   44    technician    single  secondary      no       29     yes   no   
2   33  entrepreneur   married  secondary      no        2     yes  yes   
3   47   blue-collar   married    unknown      no     1506     yes   no   
4   33       unknown    single    unknown      no        1      no   no   
5   35    management   married   tertiary      no      231     yes   no   
6   28    management    single   tertiary      no      447     yes  yes   
7   42  entrepreneur  divorced   tertiary     yes        2     yes   no   
8   58       retired   married    primary      no      121     yes   no   
9   43    technician    single  secondary      no      593     yes   no   

   contact  day month  durations  campaign  pdays  previous poutcome   y  
0  u

# cross tab
# difference b/w cross tab and pivot 
# The function does not require a dataframe as an input. 
# It can also accept array-like objects for its rows and columns.
# The function can normalize the resulting dataframe, meaning that the values displayed can be displayed as percentage 
# of row or column totals.
# The default function is len (count), whereas the pivot table one is numpy’s mean function.

x=pd.crosstab(index= df.MaritalStatus  ,
              columns= df.Gender  ,
               values= df.Income  ,
               aggfunc   ='sum')
print(x)
#A key benefit of the crosstab function over the Pandas Pivot Table function is that it allows you to normalize the resulting 
#dataframe, returning values displayed as percentages.
#This goes one step further – the normalize argument accepts a number of different options:

#‘all’ or True – normalizes the values across the entire dataframe (as a percentage of the total across rows and columns)
#‘index’ – normalizes across rows
#‘columns’ – normalizes down columns
x1=pd.crosstab(index= df.MaritalStatus  ,
              columns= df.Gender  
              )
#Pandas will generate a crosstab which counts the number of times each item appears (the length of that series)
print(x1)
x2=pd.crosstab(index= df.MaritalStatus  ,
              columns= df.Gender  ,normalize= 'index'
              )
print(x2)

In [16]:
x3=pd.pivot_table(
            data =df,
            index='marital',
            columns='job',
            values='balance',
            aggfunc='mean')
print(x3.head(10))

job            admin.  blue-collar  entrepreneur    housemaid   management  \
marital                                                                      
divorced   878.333333   820.806667   1155.983240  1573.222826  1618.073807   
married   1281.409580  1113.165901   1642.145931  1248.173246  1828.159444   
single    1020.739005  1056.105263   1248.235294  2074.743056  1700.219545   

job           retired  self-employed     services      student   technician  \
marital                                                                       
divorced  1507.835294    2426.350000   834.304189  1101.000000   924.048649   
married   2140.098787    1644.948640  1088.847528  1164.796296  1307.399556   
single    1360.388889    1410.365471   887.324708  1403.753986  1283.938168   

job        unemployed      unknown  
marital                             
divorced  1409.643275  1706.294118  
married   1568.632011  1788.128079  
single    1484.079800  1741.794118  


In [7]:
#crosstab function
pd.crosstab(df.Education, df.Gender)


Gender               Female  Male
Education                        
Bachelors               146   155
Graduate Degree          93    79
High School              80    99
Partial College         132   129
Partial High School      38    38

In [8]:
pd.crosstab(index = df.Education, columns = df.Gender, values = df.Age, aggfunc = 'mean')

Gender                  Female       Male
Education                                
Bachelors            45.965753  44.851613
Graduate Degree      43.054348  47.131579
High School          45.150000  43.224490
Partial College      43.530303  42.622047
Partial High School  39.947368  44.131579

In [29]:
 df.iloc[1:3,:]

age           job  marital  education default  balance housing loan  \
1   44    technician   single  secondary      no       29     yes   no   
2   33  entrepreneur  married  secondary      no        2     yes  yes   

   contact  day month  durations  campaign  pdays  previous poutcome   y  
1  unknown    5   may        151         1     -1         0  unknown  no  
2  unknown    5   may         76         1     -1         0  unknown  no

In [30]:
 df.iloc[1:3,]

age           job  marital  education default  balance housing loan  \
1   44    technician   single  secondary      no       29     yes   no   
2   33  entrepreneur  married  secondary      no        2     yes  yes   

   contact  day month  durations  campaign  pdays  previous poutcome   y  
1  unknown    5   may        151         1     -1         0  unknown  no  
2  unknown    5   may         76         1     -1         0  unknown  no

In [31]:
 df.iloc[1:3]

age           job  marital  education default  balance housing loan  \
1   44    technician   single  secondary      no       29     yes   no   
2   33  entrepreneur  married  secondary      no        2     yes  yes   

   contact  day month  durations  campaign  pdays  previous poutcome   y  
1  unknown    5   may        151         1     -1         0  unknown  no  
2  unknown    5   may         76         1     -1         0  unknown  no

In [32]:
 df.iloc[3,1:4]

job          blue-collar
marital          married
education        unknown
Name: 3, dtype: object

In [33]:
 df.iloc[-1,:]

age                   57
job          blue-collar
marital          married
education      secondary
default               no
balance              668
housing               no
loan                  no
contact        telephone
day                   17
month                nov
durations            508
campaign               4
pdays                 -1
previous               0
poutcome         unknown
y                     no
Name: 45209, dtype: object

In [34]:
 df.loc[1,'age']

44

In [35]:
df.loc[1:4,['age','marital']]

age  marital
1   44   single
2   33  married
3   47  married
4   33   single

In [36]:
df.loc[1:4,]

age           job  marital  education default  balance housing loan  \
1   44    technician   single  secondary      no       29     yes   no   
2   33  entrepreneur  married  secondary      no        2     yes  yes   
3   47   blue-collar  married    unknown      no     1506     yes   no   
4   33       unknown   single    unknown      no        1      no   no   

   contact  day month  durations  campaign  pdays  previous poutcome   y  
1  unknown    5   may        151         1     -1         0  unknown  no  
2  unknown    5   may         76         1     -1         0  unknown  no  
3  unknown    5   may         92         1     -1         0  unknown  no  
4  unknown    5   may        198         1     -1         0  unknown  no

In [37]:
 df.iloc[1:4,]

age           job  marital  education default  balance housing loan  \
1   44    technician   single  secondary      no       29     yes   no   
2   33  entrepreneur  married  secondary      no        2     yes  yes   
3   47   blue-collar  married    unknown      no     1506     yes   no   

   contact  day month  durations  campaign  pdays  previous poutcome   y  
1  unknown    5   may        151         1     -1         0  unknown  no  
2  unknown    5   may         76         1     -1         0  unknown  no  
3  unknown    5   may         92         1     -1         0  unknown  no

In [39]:
df[['age','marital']]

age   marital
0       58   married
1       44    single
2       33   married
3       47   married
4       33    single
...    ...       ...
45205   25    single
45206   51   married
45207   71  divorced
45208   72   married
45209   57   married

[45210 rows x 2 columns]

In [40]:
df.head(10)

age           job   marital  education default  balance housing loan  \
0   58    management   married   tertiary      no     2143     yes   no   
1   44    technician    single  secondary      no       29     yes   no   
2   33  entrepreneur   married  secondary      no        2     yes  yes   
3   47   blue-collar   married    unknown      no     1506     yes   no   
4   33       unknown    single    unknown      no        1      no   no   
5   35    management   married   tertiary      no      231     yes   no   
6   28    management    single   tertiary      no      447     yes  yes   
7   42  entrepreneur  divorced   tertiary     yes        2     yes   no   
8   58       retired   married    primary      no      121     yes   no   
9   43    technician    single  secondary      no      593     yes   no   

   contact  day month  durations  campaign  pdays  previous poutcome   y  
0  unknown    5   may        261         1     -1         0  unknown  no  
1  unknown    5   may        151         1     -1         0  unknown  no  
2  unknown    5   may         76         1     -1         0  unknown  no  
3  unknown    5   may         92         1     -1         0  unknown  no  
4  unknown    5   may        198         1     -1         0  unknown  no  
5  unknown    5   may        139         1     -1         0  unknown  no  
6  unknown    5   may        217         1     -1         0  unknown  no  
7  unknown    5   may        380         1     -1         0  unknown  no  
8  unknown    5   may         50         1     -1         0  unknown  no  
9  unknown    5   may         55         1     -1         0  unknown  no

In [3]:
df.head(5)

ID Marital Status  Gender   Income  Children        Education  \
0  12496        Married  Female  40000.0       1.0        Bachelors   
1  24107        Married    Male  30000.0       3.0  Partial College   
2  14177        Married    Male  80000.0       5.0  Partial College   
3  24381         Single     NaN  70000.0       0.0        Bachelors   
4  25597         Single    Male  30000.0       0.0        Bachelors   

       Occupation Home Owner  Cars Commute Distance   Region   Age  \
0  Skilled Manual        Yes   0.0        0-1 Miles   Europe  42.0   
1        Clerical        Yes   1.0        0-1 Miles   Europe  43.0   
2    Professional         No   2.0        2-5 Miles   Europe  60.0   
3    Professional        Yes   1.0       5-10 Miles  Pacific  41.0   
4        Clerical         No   0.0        0-1 Miles   Europe  36.0   

  Purchased Bike  
0             No  
1             No  
2             No  
3            Yes  
4            Yes

# how do you melt a dataframe
#df.melt used for melting a dataframe
#melt a dataframe means unpivoting a dataframe from wide format to long

In [8]:
import pandas as pd
df2=pd.DataFrame({'A': [1,2,3,4,5] ,
                  'B': [10,11,12,13,14] ,
                  'C': ['NEW','NEW2','NEW3','NEW4','NEW5'] ,
                  'D': ['TYPE1','TYPE2','TYPE3','TYPE4','TYPE5']
                  })
print(df2)
print(df2.reset_index())
df3=df2.melt(id_vars=['A'],value_vars=['B'])
print(df3)

   A   B     C      D
0  1  10   NEW  TYPE1
1  2  11  NEW2  TYPE2
2  3  12  NEW3  TYPE3
3  4  13  NEW4  TYPE4
4  5  14  NEW5  TYPE5
   index  A   B     C      D
0      0  1  10   NEW  TYPE1
1      1  2  11  NEW2  TYPE2
2      2  3  12  NEW3  TYPE3
3      3  4  13  NEW4  TYPE4
4      4  5  14  NEW5  TYPE5
   A variable  value
0  1        B     10
1  2        B     11
2  3        B     12
3  4        B     13
4  5        B     14


In [ ]:
pd.concat([df1,df2],axis=0) # axis =0 row wise, axis==1 column wise
pd.merge(df1,df2,on='column name',how='Left')
pd.merge(df1,df2[['col','col2']],on =,how)

In [68]:

df.isnull()
df.isnull().sum()
df.dropna()#  drop any row which contain null
df.dropna(axis=1) # drop col whcih contain any null /missing value

df3=df.drop(['pdays'],axis=1)# dop a coloumn by name
df3.head()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
durations    0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
dtype: int64

In [80]:
df6=df.head(10)
print(df6)
df6.set_index('marital')# set any column as a index


   age           job   marital  education default  balance housing loan  \
0   58    management   married   tertiary      no     2143     yes   no   
1   44    technician    single  secondary      no       29     yes   no   
2   33  entrepreneur   married  secondary      no        2     yes  yes   
3   47   blue-collar   married    unknown      no     1506     yes   no   
4   33       unknown    single    unknown      no        1      no   no   
5   35    management   married   tertiary      no      231     yes   no   
6   28    management    single   tertiary      no      447     yes  yes   
7   42  entrepreneur  divorced   tertiary     yes        2     yes   no   
8   58       retired   married    primary      no      121     yes   no   
9   43    technician    single  secondary      no      593     yes   no   

   contact  day month  durations  campaign  pdays  previous poutcome   y  
0  unknown    5   may        261         1     -1         0  unknown  no  
1  unknown    5   may   

# numpy

# Difference between numpy array and list

#numpy array consume much less memory and give much faster opertion as compared to list
list contain hetrogeneous data whereas numpy contain homogeneous data.

In [1]:
import numpy as np
#create one D array

a=np.array([1,2,3,4,5,6,7,8])  

#print all the elements
x=a[:]
#indexing start with 0 for numpy array
#slicing operation
x1=a[0:4]
x2=a[-4:-1]  #but -1 to -4 give empty
#mutate the array ,change the elemnent value 
a[0]=90
print(a)
#print(x3)
a=np.array([1,2,3,4,5,6,7,8])
b=np.array([1,2,3,4,5,6,7,8])
print(a[a>4])   # give values 

# create 2-d array
a=np.array([[1,2,3],[4,5,6]])
#print(a.size)      # give number of elements
#print(np.ndim(a))  # dimension of the array
#print(np.size(a))
#print(a[1:1])      #give empty
#print(a[1,2])
 
    #print(a[1,:])
#print(a[:,2])
#print(a.sum(axis=1))  #by row (axis =1)
b=np.arange(0,30).reshape(15,2)
#c=b>12
print(b.stddev())

 

ary1=[[1,2,3,4],[5,6,7,8],[9,10,11,12]]
ary2=[1,2,3,4]
ary3=np.array(ary1)
ary4=np.array(ary2)

#y=ary3[0:2,1:3]

x=ary3.sum(axis=1)
#print(type(ary1))
print(x)
 

 
x=np.arange(30).reshape(3,5,2)
print(x)
print(x[1][::2][1])# 3, represent 3 dimension each has 5 rows 2 coloumns print me 1 represent 1 dimension first argument in print 
#represent from whcih dimension value need to select 0,1,2,,second argument whcih row need to fetch row number start with 0

 
x = np.array([[0, 1], [1, 1], [2, 2]])
y = x.sum(-1)
print(y)
print(x[y < 2, :])


 
#arr=[3,4,5,7,8,9,18,34]
#arr1=np.array(arr)
#print(type(arr1))
    
#print(arr1[0:2:6])
#print(arr2)

#important


IndentationError: unexpected indent (93076185.py, line 28)

In [30]:
#multidimensinal array
ary3=[[1,2],[3,4]]
ary4=[[4,5],[3,4]]
a=np.array(ary3)
b=np.array(ary4)
c=a*b
print(c)

[[ 4 10]
 [ 9 16]]


In [25]:
###
print(np.sqrt(a))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [ ]:
print(np.std(a))

In [31]:
#arithemetic operation on two np array
print('add')
print(np.add(a,b))
print('subtract')
print(np.subtract(a,b))
print('multiply')
print(np.multiply(a,b))
print('divide')
print(np.divide(a,b))
x=np.array([1,2,3,4])
print(np.exp(x))
print('exponantial')
print(np.sqrt(x))
print('power')
print(np.power(x,2))
a=np.array([[1,2,3],[4,5,6]])
print('2d array')
print(a)

add
[[5 7]
 [6 8]]
subtract
[[-3 -3]
 [ 0  0]]
multiply
[[ 4 10]
 [ 9 16]]
divide
[[0.25 0.4 ]
 [1.   1.  ]]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
exponantial
[1.         1.41421356 1.73205081 2.        ]
power
[ 1  4  9 16]
2d array
[[1 2 3]
 [4 5 6]]


In [32]:
############
# example of for loop
for x in range(1,10):
    print(x)

1
2
3
4
5
6
7
8
9


In [ ]:


#x = np.array([[-2], 
 #             [2]])
#y = np.array([[-3, 3]])
#print(x.dot(y))
#import numpy as np

x = np.array([[-2], 
              [2]])
y = np.array([[-3, 3]])
print(x + y)
x = np.arange(4)
print (x)
print(x**2)

In [26]:
x=np.arange(1,10).reshape(3,3)
print(x.shape)

(3, 3)


In [19]:
print(x.ndim)

2


In [20]:
print(x.itemsize)

4


In [21]:
print(x.dtype)

int32


In [1]:
import numpy as np

x = np.arange(12).reshape(3,4)
print(x[:,1])

[1 5 9]


In [17]:
import numpy as np

x = np.arange(4)
print(x.flatten())

[0 1 2 3]


In [10]:
#####3 statistic on array 
a=np.array([[20,10,8,4,5],[2,3,4,5,6]])
print(a)

[[20 10  8  4  5]
 [ 2  3  4  5  6]]


In [13]:
print(np.sum(a))           #  sum of all the elements

67


In [14]:
print(np.sum(a, axis =0))  # sum by column

[22 13 12  9 11]


In [15]:
print(np.mean(a,axis =0))  # mean by column

[11.   6.5  6.   4.5  5.5]


In [16]:
print(np.sort(a,axis =0))  # sort by column

[[ 2  3  4  4  5]
 [20 10  8  5  6]]


In [12]:
print(a.sum())

67


In [11]:
print(a)
# in mumpy  1  row 0 =col

[[20 10  8  4  5]
 [ 2  3  4  5  6]]


In [6]:
#####
  #np.empty(), np.arange(), np.linspace()
####
print(np.arange(1, 100,4))

#generate sequence of numbers starting with 1 and eqally spaced with 4 and excluded 100   

[ 1  5  9 13 17 21 25 29 33 37 41 45 49 53 57 61 65 69 73 77 81 85 89 93
 97]


In [22]:
 #important    nditer used to iterate over the elements of 1d,2d, array
x=np.array([[1,2,3],[4,5,6]])
for i in np.nditer(x):
    print(i)

1
2
3
4
5
6


In [7]:
print(np.linspace(1, 1000,4))

#genrate sequence of number basically 4 numbers including 1 nad 10000
#seed function try to create psedo randomm numbers
#basically it initialize the random function so each time it generate same random number 
#random.randint(1,1000,4) -> generate any 4 random numbers in range 1 to 10000

[   1.  334.  667. 1000.]


In [8]:
import random
 
for i in range(4):
 np.random.seed(4)
 print(np.random.randint(1, 1000,4))
    
#print(np.random.random(5))   create  5 floating number   

[123 175 440 710]
[123 175 440 710]
[123 175 440 710]
[123 175 440 710]


In [2]:
###### create special type of array 

np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [3]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [4]:
np.full((3,4),4)  

array([[4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]])

In [5]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
import pandas as pd

s1 = pd.Series([0, 1, 2, 3])
s2 = pd.Series([0, 1, 2, 3])
s3 = pd.Series([0, 1, 4, 5])
d = pd.concat([s1, s2, s3], axis=0)
#print(d)
#**************
import pandas as pd
#x=pd.date_range('11-Sep-2017', '17-Sep-2017', freq='2D')
#d = pd.date_range('11-Sep-2017', '17-Sep-2017', freq='2D')
#x=len(d[d.isin(pd.to_datetime(['12-09-2017', '15-09-2017']))])
#print(x)
import pandas as pd

df = pd.DataFrame({'A':[34, 78, 54], 'B':[12, 67, 43],'C':[10,40,50]}, index=['r1', 'r2', 'r3'])
#x=df.loc['r2']
#print(df.B)

#x=df.loc['r2':'r3']
#print(x)
#x=df.loc[(df.B > 45) & (df.C < 30)]
#print(x)
#s = pd.Series([9.2, 'hello', 89])
#print(type(s))
#x=df.iloc[:, lambda x : [0,2]]
x=df.loc[:, lambda x : x.columns.isin(['C', 'D'])]
print(x)


In [ ]:
import numpy as np
import pandas as pd
#data = [{'a': 1, 'b': 2}, {'a': 5, 'b': 10, 'c': 20}]
#df = pd.DataFrame(data, columns=['a', 'b'])
#print(df)
#s = pd.Series([89.2, 76.4, 98.2, 75.9], index=list('abcd'))
#print(s[['c', 'a']])
#df = pd.DataFrame({'A':[34, 78, 54], 'B':[12, 67, 43]}, index=['r1', 'r2', 'r3'])
#df.loc['r4'] = [67, 78]
#print(df.B)
#print(df.iloc[1])
#df.ix['C'] = [12, 98, 45]
#print(df)
df = pd.DataFrame(np.random.rand(5,3))
df

#group by
import pandas as pd
import numpy as np
file="C:\\Users\\SOHIT GOYAL\\Desktop\\excel5.csv"
df=pd.read_csv(file)
#df.head()
#x=df['state'].value_counts()
#x=df.groupby(['creditcard','state']).count()
#x=pd.pivot_table(df,index=["state","salary"],aggfunc=np.sum)
x=pd.pivot_table(df,index=["state"],values=["salary"])
#df['lalit']=df['creditcard'].apply(lambda x: x>7)
#x=df[(df.countryname=='tripura') & (df.people > 300)]
#x=df[df['countryname']=='haryana']
#x=df.groupby(['lalit','creditcard']).size()
print(x)

file="C:\\Users\\SOHIT GOYAL\\Desktop\\excel4.csv"
file1="C:\\Users\\SOHIT GOYAL\\Desktop\\excel6.csv"
df=pd.read_csv(file)
df1=pd.read_csv(file1)
#df1.head()
x=pd.merge(df,df1,on='countryname')
#to check the null mean nan value
#print(df.isnull())
#to fill na value with zero
#print(df.fillna(0))
#x=df.fillna(method="ffill")
#for column wise fill
#x=df.fillna(method="ffill",axis=1)
#x=df.fillna(method="bfill")
#df.head(22)
print(x)


import pandas as pd
file="C:\\Users\\SOHIT GOYAL\\Desktop\\excel3.csv"
df=pd.read_csv(file)
#df.head()
#groupby and and count funtion illustration
#x=df.groupby('speaker')
#lambda function illustration
#df['vfew'] = df['speaker'].apply(lambda x: x <= 30)
#x=df.groupby(['vfew','speaker'])
#x.size()
#crosstab illustration
#x=pd.crosstab(df["speaker"],df["country"],margins=True)
#pivot illustration
#x=pd.pivot_table(df,index=["country","speaker"],values=["population"])
#sort
#x=df.sort_values(by="population",ascending=False)
#x['mRank'] = x['population'].rank(ascending=1)
#x=df.rank(axis=1)
#x.head(6)



data = [{'a': 1, 'b': 2}, {'a': 5, 'b': 10, 'c': 20}]
df = pd.DataFrame(data)
print(df)

x = np.array([[3.2, 7.8, 9.2],
             [4.5, 9.1, 1.2]], dtype='int64')
print(x.itemsize)

import pandas as pd
#file="C:\\Users\\SOHIT GOYAL\\Desktop\\excel2.csv"
#file1="C:\\Users\\SOHIT GOYAL\\Desktop\\excel4.csv"
#df=pd.read_csv(file)
#df1=pd.read_csv(file1)
#merge illustrtion(giving all rows depending on the on condition)
#pd.merge(df,df1,on='country')
#illustration of left and right join
#x=pd.merge(df[['mobole','population','speaker']],df1,
 #          on='mobole',how='outer',indicator=True)
#x.head(10)
#x=df['country'].groupby(df['speaker'])
#df['vas'].value_counts()
#x=df.groupby(['country']).count

In [ ]:
print(np.random.randint(100))
print(np.random.randint(100,size=10))

print(np.random.randint(2,100,size=10))